### ISSUE TITLE
Misplaced data in workflow and statistics

### ISSUE THREAD

**Issue by maarlon** [acmenucms/menucms#2]
The data for the workflow and statistics pages is misplaced as shown on the screenshots.
![bildschirmfoto 2015-07-01 um 13 18 48](https://cloud.githubusercontent.com/assets/10742856/8453329/e998c644-1ff3-11e5-87d7-c12856db057b.png)
![bildschirmfoto 2015-07-01 um 13 18 53](https://cloud.githubusercontent.com/assets/10742856/8453331/e99c5656-1ff3-11e5-9c07-04cb5ae4dfa4.png)
![bildschirmfoto 2015-07-01 um 13 19 11](https://cloud.githubusercontent.com/assets/10742856/8453330/e99b8744-1ff3-11e5-9e8b-08d4d69511b3.png)

**Comment by acmenucms** [comment]
@maarlon that is issue with sizes of screen, so when we define min size of screen, I will setup media queries and fix this issue.

**Comment by maarlon** [comment]
@acmenucms When will you be able to fix this?

**Comment by acmenucms** [comment]
@maarlon can be closed, now data is properly displayed until 1024px
