### ISSUE TITLE
Statistics: Currency displaying

### ISSUE THREAD

**Issue by maarlon** [acmenucms/menucms#4]
The 'eur' from the database should be converted to the € sign for displaying on the statistics page. I suggest we create a new Model for the Currency, so it is easily expandable and we can use it at multiple places if needed.

**Comment by acmenucms** [comment]
@maarlon I have suggestion, actually we can add additional field in database called icon, and there we can put code for Icon ( example font awesome icon ), if you agree of course.

**Comment by maarlon** [comment]
@acmenucms Not sure if that would be efficient for the amount of data stored (also performance-wise). Something like this should be enough I guess (I took that from our Mobile API):

```php
class Currency {
    public $currencycode,
    $currency,
    $merchantaccount;
    
    public $supported = false;
    
    private $currencies = array(
        'eur' => array(
            'currencycode' => 'eur',
            'currency' => '€',
            'merchantaccount' => ''
        ),
        'chf' => array(
            'currencycode' => 'chf',
            'currency' => 'CHF ',
            'merchantaccount' => ''
        ),
        'gbp' => array(
            'currencycode' => 'gbp',
            'currency' => '£',
            'merchantaccount' => ''
        )
    );
    
    public function __construct($currencycode) {
        $this->currencycode = $currencycode;
        
        if(isset($this->currencies[$this->currencycode])) {
            $this->currencycode = $this->currencies[$this->currencycode]['currencycode'];
            $this->currency = $this->currencies[$this->currencycode]['currency'];
            $this->merchantaccount = $this->currencies[$this->currencycode]['merchantaccount'];
            
            $this->supported = true;
        } else {
            $this->supported = false;
        }
    }
}
```

**Comment by acmenucms** [comment]
@maarlon sorry but I think that solution that you have suggested is not efficient for resource usage. 
Because we already have query in database to determine which currency we use. So we can add field for hash tag for icon that we need. Solution that you have suggested will use more resources on server because then we have additional check in php and pattern matching, also we will have more code unnecessary. Of course if you want to solve this problem like you suggested, I will change code in that way.

**Comment by maarlon** [comment]
@acmenucms  In which table would the new column go?

**Comment by acmenucms** [comment]
@maarlon I suggest table restaurants, because there we already have info about currencies.

**Comment by maarlon** [comment]
@acmenucms But if for example we have 100 swiss restaurants, then we'd have the same data in the column 'icon' 100 times, right? Also as we have to store additional information about a currency (for example the merchant account, and maybe at some point exchange rates), do you think it maybe makes sense to add a table 'currencies'?

**Comment by acmenucms** [comment]
@maarlon that has most sense, if we are able to add one more table that would be great.

**Comment by maarlon** [comment]
@acmenucms Could you make the new table? Columns would be:
- currencycode
- currencyicon
- merchantaccount

**Comment by acmenucms** [comment]
@maarlon Sure I will. Just one information I need. For what is used merchantaccount field.

**Comment by maarlon** [comment]
@acmenucms The merchantaccount field is used for communication with our payment processor. For every new currency we request, our payment processor sends us a merchantaccount for that specific currency. A VARCHAR(100) should be enough.

**Comment by acmenucms** [comment]
@maarlon Thanks on info :), I will start with implementation of this feature then.
